[package]
name = "the_ray_tracer_challenge"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
lto = true
panic = "abort"

[[bin]]
name="ch7_pit"
path="src/ch7_pit/ch7_pit.rs"

[[bin]]
name="ch6_pit"
path="src/ch6_pit/ch6_pit.rs"

[[bin]]
name="ch5_pit"
path="src/ch5_pit/ch5_pit.rs"

[[bin]]
name="ch4_pit"
path="src/ch4_pit/ch4_pit.rs"

[[bin]]
name="ch3_pit"
path="src/ch3_pit/ch3_pit.rs"

[[bin]]
name="cannon"
path="src/cannon/cannon.rs"

[[bin]]
name="cannon_ppm"
path="src/cannon_ppm/cannon_ppm.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]

[dependencies]
image = "0.24.5"
ray_tracer = {path = "ray_tracer"}
