[package]
name = "the_ray_tracer_challenge"
version = "0.1.0"
edition = "2021"


[[bin]]
name="cannon"
path="src/cannon/cannon.rs"

[[bin]]
name="cannon_ppm"
path="src/cannon_ppm/cannon_ppm.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]

[dependencies]
image = "0.24.5"
ray_tracer = {path = "ray_tracer"}
