[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.5"

[profile.release]
lto = true
panic = "abort"

[profile.release_debug_info]
inherits = "release"
debug = true
